import { useCallback, useEffect, useState } from "react";
import { Card } from "../components/Card";
import { StatusBlock } from "../components/StatusBlock";
import { webConfig } from "../config";
import type { ExtractionLogItem } from "../types/admin";

export function AdminLogsPage() {
  const [logs, setLogs] = useState<ExtractionLogItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [errorText, setErrorText] = useState<string | null>(null);

  const loadLogs = useCallback(async () => {
    setIsLoading(true);

    try {
      const response = await fetch(`${webConfig.apiBaseUrl}/api/extractions`);

      if (!response.ok) {
        const payload = (await response.json().catch(() => null)) as { error?: string } | null;
        setErrorText(payload?.error ?? `Failed to load logs: ${response.status}`);
        return;
      }

      const payload = (await response.json()) as ExtractionLogItem[];
      setLogs(payload);
      setErrorText(null);
    } catch {
      setErrorText("Failed to reach API endpoint while loading extraction logs.");
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    void loadLogs();
  }, [loadLogs]);

  return (
    <div className="page-grid">
      <Card title="Admin Logs">
        <p>Review extraction/request history generated by the API.</p>
        <div className="admin-actions">
          <button className="secondary-button" type="button" onClick={() => void loadLogs()}>
            Refresh logs
          </button>
        </div>
      </Card>

      {(isLoading || errorText) && (
        <Card title="Logs status">
          <StatusBlock loadingText="Loading extraction logs..." errorText={errorText} successText={null} />
        </Card>
      )}

      <Card title="Extraction history">
        {!isLoading && logs.length === 0 && <p>No extraction logs found yet.</p>}

        {logs.length > 0 && (
          <ul className="plain-list">
            {logs.map((logItem) => (
              <li key={logItem.id} className="admin-list-item">
                <div>
                  <strong>#{logItem.id}</strong> — {new Date(logItem.createdAtUtc).toLocaleString()}
                  <div className="muted-text">
                    Skills: {logItem.skillCount} · Warnings: {logItem.warningCount}
                  </div>
                  <div className="card-note">{logItem.summary}</div>
                </div>
              </li>
            ))}
          </ul>
        )}
      </Card>
    </div>
  );
}